#!/usr/bin/env bash

URL="$1"
EXTRA_OPTIONS="$2"

doCurl() {
  local fileName="/tmp/datamart-$1.tmp"
  options="-HDatamart:$1"
  [ -n "$EXTRA_OPTIONS" ] && options+=" $EXTRA_OPTIONS"
  echo "DATAMART -- $1" > $fileName
  curl -s "$options" "$URL" | jq . >> $fileName
}


doCurl 'false'
doCurl 'true'

diff --width=275 -i -y /tmp/datamart-false.tmp /tmp/datamart-true.tmp

echo ""
