#!/usr/bin/env bash

HEADERS=""
OPTIONS=""
usage() {
cat <<EOF
$0 [options] <url>

Options:
  -h,--help   Print this help and exit
  -t,--token  User Access Token
  -H          Header Value

$1
EOF
exit
}

ARGS=$(getopt -n $(basename ${0}) \
    -l "help,token:" \
    -o "ht:H:sk" -- "$@")
[ $? != 0 ] && usage
eval set -- "$ARGS"
while true
do
  case "$1" in
    --debug) set -x;;
    -h|--help) usage "halp! what this do?";;
    -H) HEADERS+="-H $2 ";;
    -k) OPTIONS+="k";;
    -s) OPTIONS+="s";;
    -t|--token) TOKEN="$2";;
    --) shift;break;;
  esac
  shift;
done

URL="$1"

[ -n "$OPTIONS" ] && OPTIONS="-$OPTIONS" 
[ -z "$TOKEN" ] && TOKEN="$MTOKEN"

curl $OPTIONS -H "Authorization: Bearer $TOKEN" -H "User-Agent: shanktopus/54.0" $HEADERS"$URL"
