#!/usr/bin/env bash

CURRENT_BRANCH=$(git branch | grep '*' | cut -d ' ' -f 2)

echo "Current Branch is '$CURRENT_BRANCH'"

# If there are changes, we don't want to go any further
if [ $(git status | grep -c 'nothing to commit') -eq 0 ]
then
  echo 'Changes exist that can be pushed.'
  git status
  exit 1
fi

# Get the most up to date changes from master
git checkout master
git pull

# Get back to the branch we were on originally
git checkout $CURRENT_BRANCH

# Merge with no commit
echo '==================== Merge ===================='
git merge --no-commit master

exit 0

