#!/usr/bin/env bash

if [ -p /dev/stdin ]; then
  cat | jq . | less
elif [ -n "$1" ]; then
  [ ! -f "$1" ] && echo "File Not Found!" && exit 1
  cat $1 | jq . | less
else
  echo "No Input!"
  exit 1
fi

exit 0
