#!/usr/bin/env bash

DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | cut -d '/' -f4)

echo "Found Default Branch: $DEFAULT_BRANCH"

git checkout $DEFAULT_BRANCH && git pull -q

for branch in $(git branch | grep -v "$DEFAULT_BRANCH")
do
  git branch -D $branch
done
